backend:
  name: git-gateway
  branch: dev # Branch to update (optional; defaults to master)
  repo: PTA-Site

media_folder: "/pta/public/upload" # Folder where user uploaded files should go
public_folder: "/upload"

collections: # A list of collections the CMS should be able to edit
  - name: "SoTeam" # Used in routes, e.g., /admin/collections/:slug/edit
    label: "SLT" # Used in the UI, e.g., "New Post"
    folder: "pta/content/slt" # The path to the folder where the documents are stored
    slug: "{{name}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {
          label: "Image",
          name: "image",
          widget: "image",
          required: true,
          preview_path: "/upload/{{filename}}",
        }
      - {
          label: "Name",
          name: "name",
          widget: "string",
          tagname: "h4",
          required: true,
        }
      - {
          label: "Email",
          name: "email",
          widget: "string",
          tagname: "a",
          required: true,
        }
  - name: "ContactUs" 
    label: "Board Members" 
    folder: "pta/content/staff"
    slug: "{{name}}"
    create: true 
    fields:
      - {
          label: "Image",
          name: "image",
          widget: "image",
          required: true,
          preview_path: "/upload/{{filename}}",
        }
      - {
          label: "Name",
          name: "name",
          widget: "string",
          tagname: "h4",
          required: true,
        }
      - {
          label: "Role",
          name: "roles",
          widget: "string",
          tagname: "h4",
          required: true,
        }
      - {
          label: "Email",
          name: "email",
          widget: "string",
          tagname: "a",
          required: true,
        }
  - name: "Events" 
    label: "Event" 
    slug: "{{year}}"
    folder: "pta/content/events" 
    create: true 
    fields: 
      - {
          label: "Title",
          name: "title",
          widget: "string",
          required: true,
          pattern:
            [
              "^.{5,30}$",
              "Must have more than 5 characters and less than 30 characters",
            ],
        }
      - { label: "Month (MM)", name: "month", widget: "string", required: true }
      - { label: "Date (DD)", name: "date", widget: "string", required: true }
      - { label: "Year (YYYY)", name: "year", widget: "number", required: true }
      - { label: "Time", name: "time", widget: "string", required: false }
      - {
          label: "Description",
          name: "description",
          widget: "string",
          required: true,
          pattern:
            [
              "^.{10,500}$",
              "Must have more than 10 characters and less than 500 characters",
            ],
        }
      - { label: "Event Sign Up Link", name: "link", widjet: "string", required: true}
  - name: "Minutes"
    create: true 
    label: "Meeting Minutes Links"
    slug: "{{year}}-{{month}}"
    folder: "pta/content/minutes" 
    fields: 
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "link", name: "link", widget: "string", required: true }
  - name: "Gallery"
    preview_path: "/upload/{{filename}}"
    label: "Gallery Images"
    folder: "pta/content/gallery" 
    slug: "{{title}}"
    create: true 
    fields: 
      - { label: "Title", name: "title", widget: "string", required: true }
      - {
          label: "Image",
          name: "image",
          widget: "image",
          required: true,
          preview_path: "/upload/{{filename}}",
        }
  - name: "Wall of Gratitude" 
    preview_path: "/upload/{{filename}}" 
    label: "Wall of gratitude" 
    folder: "pta/content/wallofgratitude"
    slug: "{{title}}"
    create: true 
    fields:
      - { label: "Year (YYYY)", name: "year", widget: "number", required: true }
      - { label: "Name", name: "name", widget: "string", required: true }
      - {
          label: "Image",
          name: "image",
          widget: "image",
          required: true,
          preview_path: "/upload/{{filename}}",
        }
      - {
          label: "Message",
          name: "message",
          widget: "string",
          required: true,
          pattern:
            [
              "^.{10,500}$",
              "Must have more than 10 characters and less than 500 characters",
            ],
        }

