backend:
  name: git-gateway
  branch: dev # Branch to update (optional; defaults to master)
  repo: PTA-Site

media_folder: "/pta/public/upload" # Folder where user uploaded files should go
public_folder: "/pta/public/upload"

collections: # A list of collections the CMS should be able to edit
  - name: 'ContactUs' # Used in routes, e.g., /admin/collections/:slug/edit
    label: 'Staff' # Used in the UI, e.g., "New Post"
    folder: "pta/content-app/content/staff" # The path to the folder where the documents are stored   
    fotmat: "frontmatter"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: "Image", name: "image", widget: "image", required: true }
      - {
          label: "Name",
          name: "name",
          widget: "string",
          tagname: "h4",
          required: true,
        }
      - {
          label: "Role",
          name: "roles",
          widget: "string",
          tagname: "h4",
          required: true,
        }
      - {
          label: "Email",
          name: "email",
          widget: "string",
          tagname: "a",
          required: true,
        }
  - name: 'Events' # Used in routes, e.g., /admin/collections/:slug/edit
    label: 'New Event'  # Used in the UI, e.g., "New Post"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    folder: "pta/content-app/content/events" # The path to the folder where the documents are stored
    fotmat: "frontmatter"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Name",
          name: "name",
          widget: "string",
          tagname: "h4",
          required: true,
        }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Intro Blurb", name: "description", widget: "text" }
  - name: 'Minutes' # Used in routes, e.g., /admin/collections/:slug/edit
    label: 'Minutes'  # Used in the UI, e.g., "New Post"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    folder: "pta/content-app/content/minutes" # The path to the folder where the documents are stored
    fotmat: "frontmatter"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Link", name: "link", widget: "link" }
  - name: 'Photo Gallery' # Used in routes, e.g., /admin/collections/:slug/edit
    label: 'Photo Gallery'  # Used in the UI, e.g., "New Post"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    folder: "pta/content-app/content/gallery" # The path to the folder where the documents are stored
    fotmat: "frontmatter"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: "Image", name: "image", widget: "image", required: true }
      - { label: "Alternative Text", name: "text", widget: "text" }